spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
management:
  tracing:
    exporter:
      zipkin:
        endpoint: http://tracing-server:9411/api/v2/spans
        useShortTraceIds: true
eureka:
  client:
    serviceUrl: http://discovery-server:8761/eureka/
